### ISSUE TITLE
Move images inside folder

### ISSUE THREAD

**Issue by ToniRV** [ToniRV/Constraint-Satisfaction-Notebook#1]
@sharanraja Move Algorithm images to ```images``` folder.
So everything looks clean.

**Comment by ToniRV** [comment]
Hey @sharanraja, I have moved all images inside of the ```images``` folder to have it clean.
Ofc now the links are broken, make sure you update them 👍 
Also, I used my own screenshot for the backtracking algorithm instead of the Algorithm4.png image, it was quite blurry because it was not taken on a high-resolution window.
Make sure that your screenshots are good in terms of resolution, trick is to zoom the image in your screen, take a screenshot and then upload it by specifying the width.

**Comment by sharanraja** [comment]
Changed the links now, but what do you mean that the images have low resolution. Is it just that one picture or everything? Because for all the pics have bigger fonts than the one in notebook and they are also clear.

**Comment by ToniRV** [comment]
Have a look at the backtracking algorithm and compare with AC-1/AC-3, the quality is different.

**Comment by sharanraja** [comment]
Done
