### ISSUE TITLE
Constraint Propagation in CSPs

### ISSUE THREAD

**Issue by ToniRV** [ToniRV/Constraint-Satisfaction-Notebook#5]
@sharanraja Deadline Wednesday morning after the lecture.

**Comment by sharanraja** [comment]
I have the code ready for AC3 and AC1 but I am unable to run the doc even after installing all the required modules from requirements.txt.

**Comment by sharanraja** [comment]
Added sudoku example for AC-3

**Comment by sharanraja** [comment]
Added AC1 and cleaned up the Constraint propagation section
